# Generated by Django 2.1.2 on 2018-10-29 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloodcamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('place', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='bloodcampdonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=15)),
                ('date', models.DateField(auto_now=True)),
                ('blood', models.CharField(choices=[('A+', 'A-'), ('A-', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('bloodcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodcamps.bloodcamp')),
            ],
        ),
    ]
