# Generated by Django 2.1.2 on 2018-10-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcamps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcamp',
            name='date',
            field=models.DateField(),
        ),
    ]
